### ISSUE TITLE
Ajouter l'architecture, la configuration, l'installation, la mise en production, etc..

### ISSUE THREAD

**Issue by pascalfares** [JosephMansour805ATPC22018/eAS#1]
Décrire l'architecture globale et les serveurs d'applications utilisés. Ajouter aussi les documents nécessaire à la mise en place du système. Éventuellement en créer un container docker (plus simple a installer peut-être!)

**Comment by josephmansour** [comment]
eAS ne nécessite pas de serveurs supplémentaires. Il doit être installé sur le serveur à administrer. La seule exigence est que le serveur puisse communiquer avec le(s) serveur(s) de messagerie (e.g. imap.gmail.com, smtp.gmail.com) sur les ports pop3/imap et smtp.
L'installation et la mise en production sont inclues dans le README.md
